[package]
name = "stegano-core-clib"
version = "0.3.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
stegano-core = { path = "../stegano-core" }

[lib]
crate-type = ["cdylib"]
